global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: 'xxx@qq.com'
  smtp_auth_username: 'xxx@qq.com'
  smtp_auth_password: '这个不是填邮箱密码，而是qq授权码'
  smtp_require_tls: false
  smtp_hello: 'qq.com'


route:
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'mail-receiver'
receivers:
  - name: 'mail-receiver'
    email_configs:
      - to: 'xxx@qq.com'