spring:
  application:
    name: kalpa-video
  datasource:
    # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/pet?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/configuration/ui
management:
  endpoints:
    web:
      exposure:
        include: '*'
    metrics:
      tags:
        application: kalpa-video