services:
  kalpa-video:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    container_name: kalpa-video
    ports:
      - "10001:8080"
    environment:
      - KALPA_ENV=env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
